FROM python:3.10-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    openjdk-21-jre-headless \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64

WORKDIR /app

RUN pip install --no-cache-dir fastapi uvicorn[standard] pyspark==3.5.2

COPY spark_manager.py .
COPY ws_server.py .

EXPOSE 8010

CMD ["uvicorn", "ws_server:app", "--host", "0.0.0.0", "--port", "8010"]
