import os
import uuid
import glob
from typing import List
from datetime import datetime, timezone

from supertable.config.defaults import logger
from supertable.utils.helper import generate_hash_uid

try:
    from supertable.config.homedir import get_app_home
except ImportError:
    def get_app_home() -> str:
        return os.path.expanduser("~/supertable")


def _now_ms() -> int:
    """UTC timestamp in milliseconds."""
    return int(datetime.now(timezone.utc).timestamp() * 1000)


class QueryPlanManager:
    """
    Small helper that:
      - Generates a stable, short hash per query + meta pointer.
      - Creates a per-table temp directory for DuckDB profile output.
      - Exposes the full path where DuckDB should write its JSON profile.
      - Optionally cleans up old plan files to keep temp tidy.

    Path resolution:
      The temp_dir and query_plan_path are always **absolute** paths rooted
      under the app home directory.  This ensures that DuckDB (which writes
      to local disk) and plan_extender (which reads back the JSON) agree on
      the file location.  Previous versions stored a relative path that
      init_connection() silently re-rooted, causing a mismatch.
    """

    def __init__(self, super_name: str, organization: str, current_meta_path: str, query: str):
        self.identity = "queries"
        self.organization = organization
        self.super_name = super_name
        self.query = query
        self.original_table = ""

        # Build an absolute temp directory rooted under the app home.
        # Matches the resolution logic in engine_common.init_connection()
        # so DuckDB's profile_output writes to the same path we read from.
        rel_temp = os.path.join(organization, super_name, "tmp")
        self.temp_dir = os.path.join(get_app_home(), "tmp", rel_temp)
        # Create once; safe for concurrent processes
        os.makedirs(self.temp_dir, mode=0o700, exist_ok=True)
        try:
            os.chmod(self.temp_dir, 0o700)
        except OSError:
            # Best effort on filesystems without POSIX mode support.
            pass
        logger.debug(f"Using temp dir {self.temp_dir}")

        # Compose a deterministic (short) hash from meta path + parsed SQL

        meta_id = current_meta_path or ""
        # Truncate hash to 16 chars to keep filenames short/cross-platform friendly
        self.query_hash = generate_hash_uid("|".join([meta_id, query]))[:16]

        self.query_id = str(uuid.uuid4())
        self.query_plan_id = self.generate_query_plan_filename(alias="plan", extension="json")
        self.query_plan_path = os.path.join(self.temp_dir, self.query_plan_id)

        # Best-effort cleanup of very old plan files (non-fatal)
        try:
            self._cleanup_old_plans(max_keep=200)
        except Exception as e:
            logger.debug(f"Plan cleanup skipped: {e}")

    def generate_query_plan_filename(self, alias: str, extension: str = "json") -> str:
        """
        Filename pattern: <utc_ms>_<short_hash>_<request_uuid>_<alias>.<ext>
        """
        utc_ms = _now_ms()
        # Include the full request UUID.  Timestamp + deterministic query hash
        # alone collides when identical queries start in the same millisecond,
        # allowing one connection's profiler to overwrite another's file.
        request_token = self.query_id.replace("-", "")
        return f"{utc_ms}_{self.query_hash}_{request_token}_{alias}.{extension}"

    # ---- Convenience for callers (optional) ----
    def profile_pragmas(self) -> List[str]:
        """
        PRAGMAs the caller (e.g., DataReader) can apply verbatim:
            con.execute("PRAGMA enable_profiling='json';")
            con.execute(f"PRAGMA profile_output='{path}';")
        """
        return [
            "PRAGMA enable_profiling='json';",
            f"PRAGMA profile_output='{self.query_plan_path}';",
        ]

    # ---- Housekeeping -------------------------------------------------------
    def _cleanup_old_plans(self, max_keep: int = 200) -> None:
        """
        Keep temp directory tidy:
          - Only looks at '*_plan.json' files generated by this manager
          - Sorts by timestamp (prefix) descending and keeps 'max_keep' newest
          - Deletes the rest (best-effort)
        """
        # Sweep every query shape, including legacy names without a UUID.
        # Per-hash cleanup leaked one-off query plans indefinitely.
        pattern = os.path.join(self.temp_dir, "*_plan.json")
        files = sorted(glob.glob(pattern), key=_extract_ts_from_filename, reverse=True)

        # Never delete a possibly active profile. Spark's bounded query timeout
        # is five minutes; one hour leaves ample margin for a profiler that is
        # still writing while ensuring abandoned/crashed files are reclaimed.
        stale_before_ms = _now_ms() - 60 * 60 * 1000
        expire_before_ms = _now_ms() - 24 * 60 * 60 * 1000
        for index, old_file in enumerate(files):
            timestamp = _extract_ts_from_filename(old_file)
            if timestamp >= stale_before_ms:
                continue
            # Reclaim every abandoned profile after one day, and also enforce
            # the bounded directory count once a file is safely past the active
            # query window.  One-off query hashes can no longer leak forever.
            if index < max_keep and timestamp >= expire_before_ms:
                continue
            try:
                os.remove(old_file)
            except FileNotFoundError:
                continue
            except Exception as e:
                logger.debug(f"Could not delete old plan file {old_file}: {e}")


def _extract_ts_from_filename(path: str) -> int:
    """
    Extract the leading millisecond timestamp from '<ts>_<hash>_plan.json'.
    Returns 0 on failure (so bad names sort to the end).
    """
    try:
        base = os.path.basename(path)
        return int(base.split("_", 1)[0])
    except Exception:
        return 0
